### ISSUE TITLE
PHP Fatal Error with laminas/laminas-crypt:^3.4

### ISSUE THREAD

**Issue by ThibaultPelloquin** [mediamonks/doctrine-extensions#17]
### Bug Report

Installing on Symfony 6.2 project with PHP 8.1

|    Q        |   A
|------------ | ------
| Version(s)  | 3.0.6

#### Summary

Get this Exception :

PHP Fatal error:  Declaration of Laminas......::has($name) must be compatible with Psr\Container\ContainerInterface::has(string $id): bool in /path/info line int

Same as described here: https://github.com/laminas/laminas-di/issues/78

#### Expected behavior

Solution: replace laminas/laminas-crypt:^3.4 by laminas/laminas-crypt:^3.10 where bug has been fixed.

**Comment by Edwin-Luijten** [comment]
Thanks a bunch! I'm preparing a new release.

**Comment by Edwin-Luijten** [comment]
Released 3.0.7. Appreciate your report and pull-requests =)
