### ISSUE TITLE
Don't mark field as changed on reverseTransform

### ISSUE THREAD

**Issue by slootjes** [MediaMonks/doctrine-extensions#2]
When reverseTransform is done the UOW does not need to be triggered that a change occured because the value after transforming is still the same in the database as before. Only an actual change of the field should trigger transform to be executed again.

**Comment by mediamonks-robert** [comment]
Just did an update which keeps track of changes between original and transformed value. Whenever the original versions still match the transformed value is restored without performing a new transformation.
